[package]
name = "day12"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bimap = "0.6.2"
color-eyre = "0.6.2"
env_logger = "0.10.0"
itertools = "0.10.5"
log = "0.4.17"
petgraph = "0.6.2"
