#[derive(Copy, Clone, PartialEq, PartialOrd, Ord, Eq, Hash)]
pub struct Item {
    pub prio: u8,
}

impl From<char> for Item {
    fn from(c: char) -> Self {
        match c {
            'a' => Item { prio: 1 },
            'b' => Item { prio: 2 },
            'c' => Item { prio: 3 },
            'd' => Item { prio: 4 },
            'e' => Item { prio: 5 },
            'f' => Item { prio: 6 },
            'g' => Item { prio: 7 },
            'h' => Item { prio: 8 },
            'i' => Item { prio: 9 },
            'j' => Item { prio: 10 },
            'k' => Item { prio: 11 },
            'l' => Item { prio: 12 },
            'm' => Item { prio: 13 },
            'n' => Item { prio: 14 },
            'o' => Item { prio: 15 },
            'p' => Item { prio: 16 },
            'q' => Item { prio: 17 },
            'r' => Item { prio: 18 },
            's' => Item { prio: 19 },
            't' => Item { prio: 20 },
            'u' => Item { prio: 21 },
            'v' => Item { prio: 22 },
            'w' => Item { prio: 23 },
            'x' => Item { prio: 24 },
            'y' => Item { prio: 25 },
            'z' => Item { prio: 26 },
            'A' => Item { prio: 27 },
            'B' => Item { prio: 28 },
            'C' => Item { prio: 29 },
            'D' => Item { prio: 30 },
            'E' => Item { prio: 31 },
            'F' => Item { prio: 32 },
            'G' => Item { prio: 33 },
            'H' => Item { prio: 34 },
            'I' => Item { prio: 35 },
            'J' => Item { prio: 36 },
            'K' => Item { prio: 37 },
            'L' => Item { prio: 38 },
            'M' => Item { prio: 39 },
            'N' => Item { prio: 40 },
            'O' => Item { prio: 41 },
            'P' => Item { prio: 42 },
            'Q' => Item { prio: 43 },
            'R' => Item { prio: 44 },
            'S' => Item { prio: 45 },
            'T' => Item { prio: 46 },
            'U' => Item { prio: 47 },
            'V' => Item { prio: 48 },
            'W' => Item { prio: 49 },
            'X' => Item { prio: 50 },
            'Y' => Item { prio: 51 },
            'Z' => Item { prio: 52 },
            _ => panic!(),
        }
    }
}
